Update webgl_build.yml

diff --git a/.github/workflows/webgl_build.yml b/.github/workflows/webgl_build.yml
--- a/.github/workflows/webgl_build.yml
+++ b/.github/workflows/webgl_build.yml
@@ -53,31 +53,11 @@ jobs:
           allowDirtyBuild: true
           buildsPath: build/merge-rogue
           buildName: merge-rogue
-          
-      - name: Ensure temporary directory exists 📂
-        run: |
-          sudo mkdir -p build/merge-rogue
-          
-      - name: Set write permissions 🛠️
-        run: |
-          sudo chmod -R 777 build/merge-rogue
-
-      - name: Copy pre-existing index.html 📄
-        run: |
-          cp WebGLTemplates/index.html build/merge-rogue/index.html
-          cp -r WebGLTemplates/TemplateData build/merge-rogue/TemplateData
-
-      - name: Ensure index.html exists 🔥
-        run: |
-          if [ ! -f "build/merge-rogue/index.html" ]; then
-            echo "Error: index.html not found in build/"
-            exit 1
-          fi
 
       - name: Upload Build Artifact 🚀
         uses: actions/upload-pages-artifact@v1
         with:
-          name: Build
+          name: merge-rogue
           path: build/merge-rogue
 
   deploy:
@@ -99,8 +79,15 @@ jobs:
         with:
           name: Build
           path: build/merge-rogue
+          
+      - name: Ensure index.html exists 🔥
+        run: |
+          if [ ! -f "build/merge-rogue/index.html" ]; then
+            echo "Error: index.html not found in build/"
+            exit 1
+          fi
 
       - name: Deploy to GitHub Pages 🌐
         uses: actions/deploy-pages@v2
         with:
-          artifact_name: Build
+          artifact_name: merge-rogue
